### ISSUE TITLE
Ask about custom script to get invoices / expense in PDF format

### ISSUE THREAD

**Issue by tho-can-code** [tankhuu/suitescript#1]
Hi @tankhuu, thank you so much for your sharing script. I would like to get invoices / expense in PDF format. Would you please have any example solve this issue before?

**Comment by tankhuu** [comment]
Hi @thosieucoi Here is the gist which using suitelet script of my friend, that I think you could use it like an example for your issue: https://gist.github.com/tankhuu/a7ed0a0ab4c0ca23d6e38b6bf493dd13

**Comment by tho-can-code** [comment]
Thank you so much for your reference @tankhuu

**Comment by tho-can-code** [comment]
Hi @tankhuu I got the error
`Error SuiteScript 2.0 entry point scripts must implement one script type function.`
with **download-invoice.js**
Would you please help me take a look at this?
